
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Academic_Staff_Engagement_Claim_Processing_System.Data.Models.Enums;

namespace Academic_Staff_Engagement_Claim_Processing_System.Data.Models
{
    public class MarksSubmission
    {
        [Key]
        public int Id { get; set; }

        // ============================================================
        // SUBMISSION REFERENCE
        // ============================================================

        [Required]
        [MaxLength(50)]
        public string SubmissionReference { get; set; } = string.Empty;

        // ============================================================
        // LECTURER
        // ============================================================

        [Required]
        [ForeignKey(nameof(Lecturer))]
        public int LecturerId { get; set; }

        public Lecturer Lecturer { get; set; } = null!;

        // ============================================================
        // COURSE ASSIGNMENT
        // ============================================================

        [Required]
        [ForeignKey(nameof(CourseAssignment))]
        public int CourseAssignmentId { get; set; }

        public CourseAssignment CourseAssignment { get; set; } = null!;

        // ============================================================
        // COURSE
        // ============================================================

        [Required]
        [ForeignKey(nameof(Course))]
        public int CourseId { get; set; }

        public Course Course { get; set; } = null!;

        // ============================================================
        // ACADEMIC PERIOD
        // ============================================================

        [Required]
        [MaxLength(20)]
        public string AcademicYear { get; set; } = string.Empty;

        [Required]
        public Semester Semester { get; set; }

        // ============================================================
        // FILE INFORMATION
        // ============================================================

        [Required]
        [MaxLength(255)]
        public string FileName { get; set; } = string.Empty;

        /*
         * This is NOT the original filename.
         *
         * It is a private R2 object key generated by the server.
         */
        [Required]
        [MaxLength(500)]
        public string FilePath { get; set; } = string.Empty;

        /*
         * SHA-256 hash of the uploaded file.
         *
         * This allows the system to verify that the file
         * has not been changed.
         */
        [Required]
        [MaxLength(64)]
        public string FileHash { get; set; } = string.Empty;

        /*
         * MIME type recorded by the server.
         */
        [Required]
        [MaxLength(100)]
        public string ContentType { get; set; } = string.Empty;

        public long FileSizeBytes { get; set; }

        // ============================================================
        // SUBMISSION INFORMATION
        // ============================================================

        public DateTime SubmittedAtUtc { get; set; }

        public MarksSubmissionStatus Status { get; set; }
            = MarksSubmissionStatus.Pending;

        // ============================================================
        // MANAGEMENT REVIEW
        // ============================================================

        [ForeignKey(nameof(ReviewedByManagement))]
        public int? ReviewedByManagementId { get; set; }

        public Management? ReviewedByManagement { get; set; }

        public DateTime? ReviewedAtUtc { get; set; }

        [MaxLength(1000)]
        public string? ReviewComment { get; set; }

        // ============================================================
        // CONCURRENCY
        // ============================================================

        /*
         * SQL Server generates this value.
         *
         * It prevents two management users from modifying
         * the same submission simultaneously without detecting
         * the conflict.
         */
        [Timestamp]
        public byte[]? RowVersion { get; set; }
    }
}

